### PR TITLE
fixup: verbosity distributed print

### PR DESCRIPTION
**Pull request by allaffa**
Fixup #97 for use of CPU vs GPU

### CODE REVIEW

**Comment by allaffa** [comment]
@streeve 

I did the following sequence of operations: 

1. git reset to last commit of the main branch
2. git commit by smashing all the changes of the current branch into a single commit
3. git rebase main
4. git push --force

This solved the failures of the CI test. 
Accept and merge this PR into the main at your earliest convenience.

**Comment by streeve** [comment]
I think you needed to pull from this branch in between - your force dropped the last commit. I pushed again, hopefully it passes

**Review by streeve — APPROVED** [review]

**Comment by streeve** [comment]
I'm okay to merge - only waiting to make sure we're all on the same page

**Comment by allaffa** [comment]
@streeve 
If you want @pzhanggit to review this, considering this is a fix-up of a previous PR, shouldn't @pzhanggit also have ti retro-actively review the previous PR?

**Review by pzhanggit — APPROVED** [review]
It looks good to me. Thanks.

**Comment by streeve** [comment]
> @streeve If you want @pzhanggit to review this, considering this is a fix-up of a previous PR, shouldn't @pzhanggit also have to retro-actively review the previous PR?

I guess I didn't think of that, but that's why I linked to the previous

**Pull request merged**
