### PR TITLE
main script fixed

### PR DESCRIPTION
**Pull request by allaffa**

### CODE REVIEW

**Review by pzhanggit — COMMENTED** [review]
remove lines 9, 15 and 26?

**Comment by streeve** [comment]
> remove lines 9, 15 and 26?

@pzhanggit you can leave specific comments on the "files changed" tab

**Comment by streeve** [comment]
@allaffa this is where I'm confused - it shows that I can merge even though no one has approved it

**Comment by streeve** [comment]
The cache worked!!!!

**Review by streeve — APPROVED** [review]

**Comment by pzhanggit** [comment]
> The cache worked!!!!

Congratulations!

**Comment by pzhanggit** [comment]
> > remove lines 9, 15 and 26?
> 
> @pzhanggit you can leave specific comments by line on the "files changed" tab

I see, thanks!

**Pull request merged**
