### PR TITLE
Fixup serialized data creation

### LINKED ISSUE #24: Pickle files to transform raw data has to be done only for used dataset
Right now, if .pkl files are already in side serialized_dataset, new .pkl files are not created. 
And if no .pkl files are inside the serialized_dataset folder, then ALL of them are created when the code is run for the first time.

### PR DESCRIPTION
**Pull request by streeve**
Create directory if needed and only create new pickle files if not there. 

Fixes #24

### CODE REVIEW

**Review by pzhanggit — COMMENTED** [review]
What if we want to update an existing *pkl file?

**Review by allaffa — APPROVED** [review]

**Comment by allaffa** [comment]
@streeve 

approved, but cannot be merged due to tests failing

**Comment by allaffa** [comment]
@streeve 

I copied the changes in my own pull request to see if it make pass the test. 
I think that this pull request, as is, is not passing the test for the same reason why all the others are not passing the test.
I think that all the pull request are now contingent to mine being approved and merged first, otherwise none of the other existing merge requests can move forward. 

I would like to give you credit for this proposed change. To this effect, do you think that it is possible to "merge" two pull requests?

**Comment by streeve** [comment]
Included in #35

**Pull request closed without merging**
