### PR TITLE
Multitask

### PR DESCRIPTION
**Pull request by pzhanggit**
Added multi-task/head feature to PNN model
Will add it to the other models after review

### CODE REVIEW

**Comment by allaffa** [comment]
@pzhanggit @streeve 

The error is due to the fact that the layers inside the GCNN architecture now are named differently. 
Therefore, the old models cannot be re-loaded. I need to re-train the new models as are implemented by Pei and store the trained models to replace the old ones.

**Comment by allaffa** [comment]
@pzhanggit @streeve 

The accuracy Marko was getting in the reproduceable tests was justified by using charge and magnetic moment as additional nodal features beside the proton number. This is somewhat like cheating, because charge and magnetic moment are output of the DFT calculation, as much as the total energy. 
So I am going also to change the values with respect to which the EPSILON comparison is performed for the test to pass.

**Comment by streeve** [comment]
I see the same error as before you replaced the models in the CI

**Comment by streeve** [comment]
@allaffa  I think if you regenerate the models (again) it will work - I tried with 1 epoch and ran the test successfully

**Comment by streeve** [comment]
@pzhanggit should we add this for the other models as well?

**Comment by pzhanggit** [comment]
> @pzhanggit should we add this for the other models as well?

Yes. I am thinking to develop all the features and make them work for one model first. And then later it is straightforward to extend to other models.

**Comment by pzhanggit** [comment]
> > @pzhanggit should we add this for the other models as well?
> 
> Yes. I am thinking to develop all the features and make them work for one model first. And then later it is straightforward to extend to other models.

@streeve  Btw, how does Github work? I mean, I saw your messages through email notifications. It is not very timely and I might miss some messages. Is this the right way to communicate in Github?

**Comment by allaffa** [comment]
@pzhanggit @streeve 
Done! :)
All three pull request are ready to be merged. 
I would recommend the following order to merge the three pull requests: 

1) Sam's pull request to cache the CI requirements so that we avoid installing everything every time we need to test new capabilities
2) Pei's `multitask` pull request. 
3) My pull request from `DistributedDataParallelism`

I would like to proceed merging 1) and 2) ASAP
Then I will give you one more week to familiarize with 3)
On Friday, June 4th, I expect to merge 3) as well.

**Pull request merged**
